### PR TITLE
fix/revamp-person-page

### LINKED ISSUE #152: Invalid Heading Order on Person Page
1. Go to PersonPage in Storybook on a non-mobile size monitor.
2. Observe that Storybook is giving you an accessibility warning.

### Expected Behavior

No warnings from Storybook.  
Suggested fix:
The problem is a invalid heading order h3 -> h4 -> h6(headings of table).
you can fix by changing the table heading to h5 and using different sizes on the heading via https://protocol.mozilla.org/patterns/atoms/typographic.html#heading-elements
mzp-u-title-xs 

### Environment

All non-mobile screens for PersonFullView.

### PR DESCRIPTION
**Pull request by tohuynh**
### Link to Relevant Issue

WIP #179 
Resolves #152 

### Description of Changes

The Person page consist of 
 - seat and person images
 - person name, and seat name and area
 - contact info
 - roles info
 - legislations sponsored
 - voting record

Person Container now reflects that structure component-wise.

### Roles info
The component has a list of council member/ council president roles, one role for each term
Each council member role has a list of committee memberships, partition into current and former membership
Each committee is linked to the `/events` page with the events result filtered by the committee.id

### Legislation Sponsored
Initially hidden list of matters sponsored by the person (more work could be done on this in a future PR)

### Voting Record
Initially hidden voting records table

### Link to Forked Storybook Site

_If component changes (especially visual changes) are contained in this PR, we ask that you provide a link to a publicly viewable version of the Storybook docs site, so PR reviewers can see your changes without having to install and view your code locally._

https://tohuynh.github.io/cdp-frontend/#/people/e38abb6f86b2

_Please see `CONTRIBUTING.md` for directions on how this can be done._

### CODE REVIEW

File: src/components/Details/MinutesItemsList/DocumentsList.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const DocumentsList: FC<DocumentsListProps> = ({ documents }: DocumentsListProps
     return null;
   }
   return (
-    <details open={isExpanded} onToggle={onToggleIsExpanded}>
+    <details onToggle={onToggleIsExpanded}>
```
Comment (JacksonMaxfield) [inline src/components/Details/MinutesItemsList/DocumentsList.tsx:40]: This just a bugfix? This is only used in the event page correct?

File: src/components/Shared/Details.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+  hasBorderBottom,
+}: DetailsProps) => {
+  return (
+    <details open={defaultOpen}>
+      <Summary hasBorderBottom={hasBorderBottom}>{summaryContent}</Summary>
+      {hiddenContent}
+    </details>
+  );
+};
+
```
Comment (JacksonMaxfield) [inline src/components/Shared/Details.tsx:36]: Would love a quick comment here to make sure I am following. This is basically the default HTML `details` element just prefilled / fixed to match the rest of our + mozilla styling practices?

File: src/components/Shared/H2.tsx [hunk 3]
```diff
@@ -0,0 +1,8 @@
+import styled from "@emotion/styled";
+
+import colors from "../../styles/colors";
+
+export default styled.h2<{ hasBorderBottom?: boolean }>((props) => ({
+  paddingBottom: props.hasBorderBottom ? 8 : 0,
+  borderBottom: props.hasBorderBottom ? `1px solid ${colors.grey}` : 0,
+}));
```
Comment (JacksonMaxfield) [inline src/components/Shared/H2.tsx:8]: I guess same with all of these shared components, these are just pre-styled html tags right?

File: src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx [hunk 4]
```diff
@@ -1,6 +1,14 @@
...
+import styled from "@emotion/styled";
 import { useMediaQuery } from "react-responsive";
 import { screenWidths } from "../../../styles/mediaBreakpoints";
+import { fontSizes } from "../../../styles/fonts";
+
+const TableHeader = styled.div({
+  padding: 8,
+  fontSize: fontSizes.font_size_6,
+  fontWeight: 600,
+});
```
Comment (JacksonMaxfield) [inline src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx:11]: why not `styled.h6`?

File: src/containers/PersonContainer/CoverImage.tsx [hunk 5]
```diff
@@ -36,17 +62,23 @@ const CoverImage: FC<CoverImageProps> = ({
...
-      <CoverImg
+    <Images>
+      <img
         className="mzp-c-card-image"
         src={
           seatPictureSrc ||
           EXAMPLE_COVER_VIEWS[Math.floor(Math.random() * EXAMPLE_COVER_VIEWS.length)]
         }
-        alt={`${electoralArea || "Default Image, no Elector Seat Image Available"}`}
+        alt={`${electoralArea || ""}`}
```
Comment (JacksonMaxfield) [inline src/containers/PersonContainer/CoverImage.tsx:72]: do we have a default image stored somewhere?

File: src/containers/PersonContainer/PersonRoles.tsx [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+  /** The person's councilmember roles */
+  councilMemberRoles: Role[];
+  /** The person's non councilmember roles, partitioned by concilmember roles' date range
+   * and whether the role is active or inactive.
+   * The first list of roles are active, while the second list of roles are inactive.
+   */
+  nonCouncilMemberRoles: Record<string, Role[][]>;
+}
+
+const PersonRoles: FC<PersonRolesProps> = ({
```
Comment (JacksonMaxfield) [inline src/containers/PersonContainer/PersonRoles.tsx:22]: Top level comment: curious as to what happens when no roles are stored for a person. What gets displayed?

File: src/containers/PersonContainer/PersonRoles.tsx [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+                                  <Link
+                                    to={{
+                                      pathname: "/events",
+                                      state: {
+                                        committees: { [activeRole.body?.id as string]: true },
+                                      },
+                                    }}
+                                  >
+                                    <strong>{`${activeRole.body?.name}`}</strong>
+                                  </Link>
```
Comment (JacksonMaxfield) [inline src/containers/PersonContainer/PersonRoles.tsx:70]: Two things, this is duplicate code with the nonCouncilMemberRoles below this. May be worth it to make a generator function for this component so that if we want to update this in the future you only need to update the generator instead of two spots in the code.

Second, hot take and I know this is a _technically_ an accessibility violation but I think we links should always stay blue even after clicked / visited. Because we don't pass the body as a query parameter in the URL, when you click on any single one of these and then return back to the person page, all of them are now purple. Which imo, is a _worse_ experience than all always blue.

File: src/networking/RoleService.ts [hunk 8]
```diff
@@ -53,7 +53,7 @@ export default class RoleService extends ModelService {
           WHERE_OPERATOR.eq,
           doc(NetworkService.getDb(), COLLECTION_NAME.Person, personId)
         ),
-        where("title", WHERE_OPERATOR.eq, ROLE_TITLE.COUNCILMEMBER),
+        where("title", WHERE_OPERATOR.in, [ROLE_TITLE.COUNCILMEMBER, ROLE_TITLE.COUNCILPRESIDENT]),
```
Comment (BrianL3) [inline src/networking/RoleService.ts:56]: we will have to be careful about our usage of 'in' (and its counterpart, not-in), as we are limited by Firebase to only 1 of them per query. Just a reminder.

File: src/models/util/RoleUtilities.ts [hunk 9]
```diff
@@ -76,4 +76,77 @@ function getMostRecentRole(roles: Role[]): Role {
...
+  // sort by `nonTermRoleTitles`
+  const nonTermRoleTitles = [
+    ROLE_TITLE.CHAIR,
+    ROLE_TITLE.VICE_CHAIR,
+    ROLE_TITLE.MEMBER,
+    ROLE_TITLE.ALTERNATE,
+  ];
+  nonTermRoles.sort((a, b) => {
+    return nonTermRoleTitles.indexOf(a.title) - nonTermRoleTitles.indexOf(b.title);
+  });
```
Comment (JacksonMaxfield) [inline src/models/util/RoleUtilities.ts:117]: This is smart!

**Review by JacksonMaxfield — APPROVED** [review]
This is gorgeous. Nice work!

Some minor comments in the PR but largest comment for overall is this page is a bit slow to load but I am not worried about it for now because we have already created issues and plan to chunk / paginate the sponsored matters and voting record sections.

File: src/components/Details/MinutesItemsList/DocumentsList.tsx (hunk 1 above)
Comment (tohuynh) [reply src/components/Details/MinutesItemsList/DocumentsList.tsx:40]: Turns out you don't need to control the `open` for `details`. Yea it still works for the event page

File: src/components/Shared/Details.tsx (hunk 2 above)
Comment (tohuynh) [reply src/components/Shared/Details.tsx:36]: Yes, creating a react component to make it reusable. Don't want to keep removing the +/- sign on the right side for every use of `details` (https://protocol.mozilla.org/patterns/molecules/details.html)

File: src/components/Shared/H2.tsx (hunk 3 above)
Comment (tohuynh) [reply src/components/Shared/H2.tsx:8]: Yea just a reusable component, don't want to keep writing the padding and border style

File: src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx (hunk 4 above)
Comment (tohuynh) [reply src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx:11]: h6 would skip the order. the pages goes h1, h2, h6

File: src/containers/PersonContainer/CoverImage.tsx (hunk 5 above)
Comment (tohuynh) [reply src/containers/PersonContainer/CoverImage.tsx:72]: Yes, in /assets/images

File: src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx (hunk 4 above)
Comment (JacksonMaxfield) [reply src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx:11]: Are we not supposed to skip order?

File: src/containers/PersonContainer/PersonRoles.tsx (hunk 6 above)
Comment (tohuynh) [reply src/containers/PersonContainer/PersonRoles.tsx:22]: The top level page catches the error -- displays `Person is not a council member` See "Daniel strauss" page

File: src/containers/PersonContainer/PersonRoles.tsx (hunk 7 above)
Comment (tohuynh) [reply src/containers/PersonContainer/PersonRoles.tsx:70]: 1. sonds good
2. I saw the same problem, will add a ?body=id to the link

**Review by BrianL3 — APPROVED** [review]
Stellar work as usual.

File: src/containers/PersonContainer/PersonRoles.tsx (hunk 6 above)
Comment (JacksonMaxfield) [reply src/containers/PersonContainer/PersonRoles.tsx:22]: Our data model allows for people to be added with no Role + Seat info though. We can still track voting information for a person even if they dont have any role stored. So we definitely dont want to error.

File: src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx (hunk 4 above)
Comment (BrianL3) [reply src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx:11]: Storybook gets mad if you do. Presumably other things throw warnings as well.

File: src/containers/PersonContainer/PersonRoles.tsx (hunk 7 above)
Comment (JacksonMaxfield) [reply src/containers/PersonContainer/PersonRoles.tsx:70]: I would be fine with adding a query parameter to specify a single body sure!

**Comment by JacksonMaxfield** [comment]
I don't think this is related to this PR but when using dev tools for switching between mobile and desktop view of the linked site, I saw we had like 8 console errors that are all simply "required is not a function" or w.e. I assume somewhere in this lib we are used required instead of import

**Comment by tohuynh** [comment]
> I don't think this is related to this PR but when using dev tools for switching between mobile and desktop view of the linked site, I saw we had like 8 console errors that are all simply "required is not a function" or w.e. I assume somewhere in this lib we are used required instead of import

Something to do with video.js. I tried to dynamic import the supporting languages files for es, de, and en using require. (Couldn't figured it out)

File: src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx (hunk 4 above)
Comment (tohuynh) [reply src/components/Tables/ReactiveTableHeader/ReactiveTableHeader.tsx:11]: Order should not be skipped, for accessibility reasons

File: src/containers/PersonContainer/PersonRoles.tsx (hunk 6 above)
Comment (tohuynh) [reply src/containers/PersonContainer/PersonRoles.tsx]: Ok, here's Daniel Strauss page (he has roles nor matter sponsored)

image

Comment (tohuynh) [reply src/containers/PersonContainer/PersonRoles.tsx]: No contact info either

Comment (JacksonMaxfield) [reply src/containers/PersonContainer/PersonRoles.tsx]: That honestly works for me :joy:

Comment (JacksonMaxfield) [reply src/containers/PersonContainer/PersonRoles.tsx]: Thanks for fixing!
