### PR TITLE
admin/fix-deps

### LINKED ISSUE #111: Node Module dependency issues
### Describe the Bug

Npm install failing, "unable to resolve dependency tree" for the following libraries:

Webpack, webpack-cli, testing-library/react-hooks

### Reproduction

Simply running an npm install on a new cloned local branch

### Expected Behavior

A normal, successful npm install

### Screenshots
image
image

### Environment

_Any additional information about your environment._

-   Windows 10, WSL Ubuntu 20.04.2 LTS (GNU/Linux 4.19.128-microsoft-standard x86)
-   Browser Version: N/A
-   CDP Frontend Version: Unknown, latest as of 11/12/21

### PR DESCRIPTION
**Pull request by tohuynh**
### Link to Relevant Issue

This pull request resolves #111 

### Description of Changes

- Regenerate package-lock to remove mentions of Aallen institute
- Update firebase, storybook, eslint, webpack cli versions
- Remove some unused library

### CODE REVIEW

File: src/app/AppConfigContext.tsx [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
 import { FirebaseOptions } from "@firebase/app";
-import { Settings } from "@firebase/firestore";
+import { FirestoreSettings } from "@firebase/firestore";
 
 export interface FirebaseConfig {
   /** Firebase options to initialize firebase app */
   options: FirebaseOptions;
   /** Settings to intialize firestore */
-  settings: Settings;
+  settings: FirestoreSettings;
```
Comment (hawkticehurst) [inline src/app/AppConfigContext.tsx:9]: Nice, appreciate the improved clarity in naming.

**Review by hawkticehurst — APPROVED** [review]
Looks great!

**Review by JacksonMaxfield — APPROVED** [review]
Thank you so much for figuring this out.
