### PR TITLE
bugfixes/jump-to-sent-in-transcript

### LINKED ISSUE #109: Jump to sentence in transcript button not jumping to correct sentence
### Describe the Bug

_A clear and concise description of what the bug is._

When I use the transcript search and click the "Jump to sentence in transcript" button, it doesn't jump to the correct sentence.

### Reproduction

_Steps to reproduce the behavior:_

1. Go to https://councildataproject.org/self/#/events/0c6cb090cd07
2. Type in "3.1" in transcript search
2. Click on the "Jump to sentence in transcript" button (only one sentence will return from transcript search)

### Expected Behavior

_A clear and concise description of what you expected to happen._

The transcript to scroll to the correct sentence.

Additional note, not sure if when the user clicks on the "jump to sentence in transcript" if the video should start playing at that timepoint too.

### Screenshots

_If applicable, add screenshots to help explain your problem._

image

### Environment

_Any additional information about your environment._

(**Jackson note:** We should log all of this in the console if possible)

-   OS Version: _[e.g. macOS 11.3.1]_ Ubuntu 20.04
-   Browser Version: _[e.g. Chrome 89.0]_ Firefox 93
-   CDP Frontend Version: _[e.g. 0.5.0]_ latest

### PR DESCRIPTION
**Pull request by tohuynh**
### Link to Relevant Issue

This pull request resolves #109 

### Description of Changes

- Don't play the video at the timepoint when clicking on `jump to sentence in transcript`
- Fix the bug by navigating to the sentence's index relative to the entire list of sentences, instead of the index relative to the list of visible sentences.
- Memoized the calculation of the visible sentences. Just an optimization thing.

### CODE REVIEW

File: src/components/Details/TranscriptSearch/TranscriptItems.tsx [hunk 1]
```diff
@@ -70,11 +65,7 @@ const TranscriptItems: FC<TranscriptItemsProps> = ({
             searchQuery={searchQuery}
             speakerId={sentences[index].speaker_id}
             speakerPictureSrc={sentences[index].speaker_pictureSrc}
-            handleJumpToTranscript={handleJumpToTranscript(
-              index,
-              sentences[index].session_index,
-              sentences[index].start_time
-            )}
+            handleJumpToTranscript={handleJumpToTranscript(sentences[index].index)}
```
Comment (JacksonMaxfield) [inline src/components/Details/TranscriptSearch/TranscriptItems.tsx:68]: I think this is the bugfix right here right?

**Review by JacksonMaxfield — APPROVED** [review]

File: src/components/Details/TranscriptSearch/TranscriptItems.tsx (hunk 1 above)
Comment (tohuynh) [reply src/components/Details/TranscriptSearch/TranscriptItems.tsx:68]: `handleJumpToTranscript={handleJumpToTranscript(sentences[index].index)}`
Yep, use the sentence pre-calculated index instead of the index relative to the list of visible sentences.
